version: '3.1'

services:

  db:
    container_name: nestjs_ecoomerce_db
    image: postgres:14.5-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    container_name: nestjs_ecoomerce_adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080