version: '3.1'

services:

  db:
    container_name: nestjs_ecoomerce_db
    image: postgres:14.5-alpine
    restart: on-failure
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  adminer:
    container_name: nestjs_ecoomerce_adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    depends_on: 
      - db